### ISSUE TITLE
Cleanup integration  test

### ISSUE THREAD

**Issue by fvitt** [NCAR/musica-photo-decomp-rates#9]
Clean out old test driver code

Make improvements on "integration" code such as
- build executable in the run directory
- do we need to copy all the cross section inputs over to the build directory?

**Comment by AndrewJConley** [comment]
As I understand things, the primary data for cross-sections and quantum yields are in a collection of text files.  These are then interpolated onto the wavelength grid during model initialization.  That resulting data is then used during each timestep.  I would like to retain the initialization step in which the cross sections and quantum yields are interpolated onto the wavelength grid.  It would be good to separate the data from the code and clarify each of the interpolation methods.  I would like to load the data from a runtime-specified location.

**Comment by fvitt** [comment]
> As I understand things, the primary data for cross-sections and quantum yields are in a collection of text files. These are then interpolated onto the wavelength grid during model initialization. That resulting data is then used during each timestep. I would like to retain the initialization step in which the cross sections and quantum yields are interpolated onto the wavelength grid. It would be good to separate the data from the code and clarify each of the interpolation methods. I would like to load the data from a runtime-specified location.

I view this as a separate issue that I will try to address during code refactoring phase.
